### ISSUE TITLE
Ability to limit SPI speed

### ISSUE THREAD

**Issue by gordoste** [noah1510/LedController#16]
This looks like the best fork of this very popular but unmaintained library. It has everything I need except for the ability to set the maximum SPI transfer speed when configuring hardware SPI. (if your devices are on the end of a few metres of wire, or in a noisy environment, then interference becomes an issue). It's a trivial change - just add an optional spiSpeedMax parameter to init(), and if it's present, pass it to SPI.begin().
Another option is to allow the user to do the SPI.begin() themselves and pass it into a new function lc.init(&mySPI).
Thanks for the great work!

**Comment by noah1510** [comment]
This is already part of the controller configuration and will be part of the next release. You can set the spiTransferSpeed if you create a custom configuration. This will not be  a parameter in any of the constructors since most of the time the default value works just fine.

If you need the feature now you can clone the repository into your libraries folder instead of using the downloaded one.
