### ISSUE TITLE
error with setting MAX_SEGMENTS > 8

### ISSUE THREAD

**Issue by LennartHennigs** [noah1510/LedController#6]
Hey, 
unfortunately, setting the segments to something greater than 8 creates an error on the Nano:

```
LedController.hpp:55:28: note: type 'byte[8][8]' should match type 'byte[20][8]'
     using Matrix = C_Matrix;
```

Best
l.

**Comment by noah1510** [comment]
I almost expected that issue to come.
I think at the moment this is not working because the libraries are compiled before the your program.
While compiling the library the compiles assumes `MAX_SEGMENTS = 8` and creates the array witch a width of 20.
However while including the library MAX_SEGMENTS is overridden to 20 so the compiler expects to include a library with an array that has a width of 20 but only finds a library which has a width of 8 which causes the error.

**Comment by noah1510** [comment]
I will look into implementing a solution for this soon.
If you want to, you can try to implement a fix for this and create a pull request.
https://github.com/bartoszbielawski/LEDMatrixDriver might be a great reference on how to handle such a situation.

**Comment by noah1510** [comment]
I removed MAX_SEGMENTS the only limit on the segment count is your ram (and speed) this should solve your problems.
I want to do some more testing before I add this to the next version of the library so you have to use the version on the repository to test if it works for you.

Feedback is appreciated.

**Comment by LennartHennigs** [comment]
Cool! Thx. 
Will test it out today or tomorrow on a couple of boards and let you know...

**Comment by LennartHennigs** [comment]
Compiled and works on ESP32 and Nano. 
Thx!

**Comment by noah1510** [comment]
I will close this issue now the feature will be added in 1.7.0 after I looked for possible memory leaks and added an init function (to support more boards)

**Comment by noah1510** [comment]
Version  [v1.7.0](https://github.com/noah1510/LedController/releases/tag/v1.7.0) now includes the "unlimited" SegmentCount (There is a hardware limit though) and more fixes.
